/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as VerifyTenderIdRouteImport } from './routes/verify.$tenderId'
import { Route as VendorWithdrawRouteImport } from './routes/vendor.withdraw'
import { Route as VendorTechnicalRouteImport } from './routes/vendor.technical'
import { Route as VendorSubmitRouteImport } from './routes/vendor.submit'
import { Route as VendorRevealRouteImport } from './routes/vendor.reveal'
import { Route as VendorQaRouteImport } from './routes/vendor.qa'
import { Route as VendorDocumentsRouteImport } from './routes/vendor.documents'
import { Route as VendorComplianceRouteImport } from './routes/vendor.compliance'
import { Route as DashboardVendorsRouteImport } from './routes/dashboard.vendors'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardRevealQueueRouteImport } from './routes/dashboard.reveal-queue'
import { Route as DashboardOverviewRouteImport } from './routes/dashboard.overview'
import { Route as DashboardMembersRouteImport } from './routes/dashboard.members'
import { Route as DashboardKycReviewsRouteImport } from './routes/dashboard.kyc-reviews'
import { Route as DashboardInvitationsRouteImport } from './routes/dashboard.invitations'
import { Route as DashboardDraftsRouteImport } from './routes/dashboard.drafts'
import { Route as DashboardCustodyStatusRouteImport } from './routes/dashboard.custody-status'
import { Route as DashboardComplianceRouteImport } from './routes/dashboard.compliance'
import { Route as ApiAuthMeRouteImport } from './routes/api.auth.me'

const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTenderIdRoute = VerifyTenderIdRouteImport.update({
  id: '/verify/$tenderId',
  path: '/verify/$tenderId',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorWithdrawRoute = VendorWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => VendorRoute,
} as any)
const VendorTechnicalRoute = VendorTechnicalRouteImport.update({
  id: '/technical',
  path: '/technical',
  getParentRoute: () => VendorRoute,
} as any)
const VendorSubmitRoute = VendorSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => VendorRoute,
} as any)
const VendorRevealRoute = VendorRevealRouteImport.update({
  id: '/reveal',
  path: '/reveal',
  getParentRoute: () => VendorRoute,
} as any)
const VendorQaRoute = VendorQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => VendorRoute,
} as any)
const VendorDocumentsRoute = VendorDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => VendorRoute,
} as any)
const VendorComplianceRoute = VendorComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => VendorRoute,
} as any)
const DashboardVendorsRoute = DashboardVendorsRouteImport.update({
  id: '/dashboard/vendors',
  path: '/dashboard/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRevealQueueRoute = DashboardRevealQueueRouteImport.update({
  id: '/dashboard/reveal-queue',
  path: '/dashboard/reveal-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/dashboard/overview',
  path: '/dashboard/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: '/dashboard/members',
  path: '/dashboard/members',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardKycReviewsRoute = DashboardKycReviewsRouteImport.update({
  id: '/dashboard/kyc-reviews',
  path: '/dashboard/kyc-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInvitationsRoute = DashboardInvitationsRouteImport.update({
  id: '/dashboard/invitations',
  path: '/dashboard/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDraftsRoute = DashboardDraftsRouteImport.update({
  id: '/dashboard/drafts',
  path: '/dashboard/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCustodyStatusRoute = DashboardCustodyStatusRouteImport.update({
  id: '/dashboard/custody-status',
  path: '/dashboard/custody-status',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardComplianceRoute = DashboardComplianceRouteImport.update({
  id: '/dashboard/compliance',
  path: '/dashboard/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/vendor': typeof VendorRouteWithChildren
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/custody-status': typeof DashboardCustodyStatusRoute
  '/dashboard/drafts': typeof DashboardDraftsRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/kyc-reviews': typeof DashboardKycReviewsRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/reveal-queue': typeof DashboardRevealQueueRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/vendors': typeof DashboardVendorsRoute
  '/vendor/compliance': typeof VendorComplianceRoute
  '/vendor/documents': typeof VendorDocumentsRoute
  '/vendor/qa': typeof VendorQaRoute
  '/vendor/reveal': typeof VendorRevealRoute
  '/vendor/submit': typeof VendorSubmitRoute
  '/vendor/technical': typeof VendorTechnicalRoute
  '/vendor/withdraw': typeof VendorWithdrawRoute
  '/verify/$tenderId': typeof VerifyTenderIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/api/auth/me': typeof ApiAuthMeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/custody-status': typeof DashboardCustodyStatusRoute
  '/dashboard/drafts': typeof DashboardDraftsRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/kyc-reviews': typeof DashboardKycReviewsRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/reveal-queue': typeof DashboardRevealQueueRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/vendors': typeof DashboardVendorsRoute
  '/vendor/compliance': typeof VendorComplianceRoute
  '/vendor/documents': typeof VendorDocumentsRoute
  '/vendor/qa': typeof VendorQaRoute
  '/vendor/reveal': typeof VendorRevealRoute
  '/vendor/submit': typeof VendorSubmitRoute
  '/vendor/technical': typeof VendorTechnicalRoute
  '/vendor/withdraw': typeof VendorWithdrawRoute
  '/verify/$tenderId': typeof VerifyTenderIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/vendor': typeof VendorIndexRoute
  '/api/auth/me': typeof ApiAuthMeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/vendor': typeof VendorRouteWithChildren
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/custody-status': typeof DashboardCustodyStatusRoute
  '/dashboard/drafts': typeof DashboardDraftsRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/kyc-reviews': typeof DashboardKycReviewsRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/reveal-queue': typeof DashboardRevealQueueRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/vendors': typeof DashboardVendorsRoute
  '/vendor/compliance': typeof VendorComplianceRoute
  '/vendor/documents': typeof VendorDocumentsRoute
  '/vendor/qa': typeof VendorQaRoute
  '/vendor/reveal': typeof VendorRevealRoute
  '/vendor/submit': typeof VendorSubmitRoute
  '/vendor/technical': typeof VendorTechnicalRoute
  '/vendor/withdraw': typeof VendorWithdrawRoute
  '/verify/$tenderId': typeof VerifyTenderIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/api/auth/me': typeof ApiAuthMeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/vendor'
    | '/dashboard/compliance'
    | '/dashboard/custody-status'
    | '/dashboard/drafts'
    | '/dashboard/invitations'
    | '/dashboard/kyc-reviews'
    | '/dashboard/members'
    | '/dashboard/overview'
    | '/dashboard/reveal-queue'
    | '/dashboard/settings'
    | '/dashboard/vendors'
    | '/vendor/compliance'
    | '/vendor/documents'
    | '/vendor/qa'
    | '/vendor/reveal'
    | '/vendor/submit'
    | '/vendor/technical'
    | '/vendor/withdraw'
    | '/verify/$tenderId'
    | '/dashboard/'
    | '/vendor/'
    | '/api/auth/me'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/dashboard/compliance'
    | '/dashboard/custody-status'
    | '/dashboard/drafts'
    | '/dashboard/invitations'
    | '/dashboard/kyc-reviews'
    | '/dashboard/members'
    | '/dashboard/overview'
    | '/dashboard/reveal-queue'
    | '/dashboard/settings'
    | '/dashboard/vendors'
    | '/vendor/compliance'
    | '/vendor/documents'
    | '/vendor/qa'
    | '/vendor/reveal'
    | '/vendor/submit'
    | '/vendor/technical'
    | '/vendor/withdraw'
    | '/verify/$tenderId'
    | '/dashboard'
    | '/vendor'
    | '/api/auth/me'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/vendor'
    | '/dashboard/compliance'
    | '/dashboard/custody-status'
    | '/dashboard/drafts'
    | '/dashboard/invitations'
    | '/dashboard/kyc-reviews'
    | '/dashboard/members'
    | '/dashboard/overview'
    | '/dashboard/reveal-queue'
    | '/dashboard/settings'
    | '/dashboard/vendors'
    | '/vendor/compliance'
    | '/vendor/documents'
    | '/vendor/qa'
    | '/vendor/reveal'
    | '/vendor/submit'
    | '/vendor/technical'
    | '/vendor/withdraw'
    | '/verify/$tenderId'
    | '/dashboard/'
    | '/vendor/'
    | '/api/auth/me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  VendorRoute: typeof VendorRouteWithChildren
  DashboardComplianceRoute: typeof DashboardComplianceRoute
  DashboardCustodyStatusRoute: typeof DashboardCustodyStatusRoute
  DashboardDraftsRoute: typeof DashboardDraftsRoute
  DashboardInvitationsRoute: typeof DashboardInvitationsRoute
  DashboardKycReviewsRoute: typeof DashboardKycReviewsRoute
  DashboardMembersRoute: typeof DashboardMembersRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardRevealQueueRoute: typeof DashboardRevealQueueRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardVendorsRoute: typeof DashboardVendorsRoute
  VerifyTenderIdRoute: typeof VerifyTenderIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$tenderId': {
      id: '/verify/$tenderId'
      path: '/verify/$tenderId'
      fullPath: '/verify/$tenderId'
      preLoaderRoute: typeof VerifyTenderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/withdraw': {
      id: '/vendor/withdraw'
      path: '/withdraw'
      fullPath: '/vendor/withdraw'
      preLoaderRoute: typeof VendorWithdrawRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/technical': {
      id: '/vendor/technical'
      path: '/technical'
      fullPath: '/vendor/technical'
      preLoaderRoute: typeof VendorTechnicalRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/submit': {
      id: '/vendor/submit'
      path: '/submit'
      fullPath: '/vendor/submit'
      preLoaderRoute: typeof VendorSubmitRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/reveal': {
      id: '/vendor/reveal'
      path: '/reveal'
      fullPath: '/vendor/reveal'
      preLoaderRoute: typeof VendorRevealRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/qa': {
      id: '/vendor/qa'
      path: '/qa'
      fullPath: '/vendor/qa'
      preLoaderRoute: typeof VendorQaRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/documents': {
      id: '/vendor/documents'
      path: '/documents'
      fullPath: '/vendor/documents'
      preLoaderRoute: typeof VendorDocumentsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/compliance': {
      id: '/vendor/compliance'
      path: '/compliance'
      fullPath: '/vendor/compliance'
      preLoaderRoute: typeof VendorComplianceRouteImport
      parentRoute: typeof VendorRoute
    }
    '/dashboard/vendors': {
      id: '/dashboard/vendors'
      path: '/dashboard/vendors'
      fullPath: '/dashboard/vendors'
      preLoaderRoute: typeof DashboardVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reveal-queue': {
      id: '/dashboard/reveal-queue'
      path: '/dashboard/reveal-queue'
      fullPath: '/dashboard/reveal-queue'
      preLoaderRoute: typeof DashboardRevealQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/dashboard/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/members': {
      id: '/dashboard/members'
      path: '/dashboard/members'
      fullPath: '/dashboard/members'
      preLoaderRoute: typeof DashboardMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/kyc-reviews': {
      id: '/dashboard/kyc-reviews'
      path: '/dashboard/kyc-reviews'
      fullPath: '/dashboard/kyc-reviews'
      preLoaderRoute: typeof DashboardKycReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/invitations': {
      id: '/dashboard/invitations'
      path: '/dashboard/invitations'
      fullPath: '/dashboard/invitations'
      preLoaderRoute: typeof DashboardInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/drafts': {
      id: '/dashboard/drafts'
      path: '/dashboard/drafts'
      fullPath: '/dashboard/drafts'
      preLoaderRoute: typeof DashboardDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/custody-status': {
      id: '/dashboard/custody-status'
      path: '/dashboard/custody-status'
      fullPath: '/dashboard/custody-status'
      preLoaderRoute: typeof DashboardCustodyStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/compliance': {
      id: '/dashboard/compliance'
      path: '/dashboard/compliance'
      fullPath: '/dashboard/compliance'
      preLoaderRoute: typeof DashboardComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface VendorRouteChildren {
  VendorComplianceRoute: typeof VendorComplianceRoute
  VendorDocumentsRoute: typeof VendorDocumentsRoute
  VendorQaRoute: typeof VendorQaRoute
  VendorRevealRoute: typeof VendorRevealRoute
  VendorSubmitRoute: typeof VendorSubmitRoute
  VendorTechnicalRoute: typeof VendorTechnicalRoute
  VendorWithdrawRoute: typeof VendorWithdrawRoute
  VendorIndexRoute: typeof VendorIndexRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorComplianceRoute: VendorComplianceRoute,
  VendorDocumentsRoute: VendorDocumentsRoute,
  VendorQaRoute: VendorQaRoute,
  VendorRevealRoute: VendorRevealRoute,
  VendorSubmitRoute: VendorSubmitRoute,
  VendorTechnicalRoute: VendorTechnicalRoute,
  VendorWithdrawRoute: VendorWithdrawRoute,
  VendorIndexRoute: VendorIndexRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  VendorRoute: VendorRouteWithChildren,
  DashboardComplianceRoute: DashboardComplianceRoute,
  DashboardCustodyStatusRoute: DashboardCustodyStatusRoute,
  DashboardDraftsRoute: DashboardDraftsRoute,
  DashboardInvitationsRoute: DashboardInvitationsRoute,
  DashboardKycReviewsRoute: DashboardKycReviewsRoute,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardRevealQueueRoute: DashboardRevealQueueRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardVendorsRoute: DashboardVendorsRoute,
  VerifyTenderIdRoute: VerifyTenderIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
